# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AsciiImageConverter < Formula
  desc "Convert images into ascii art"
  homepage "https://github.com/TheZoraiz/ascii-image-converter"
  version "1.8.0-next"
  license "Apache 2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TheZoraiz/ascii-image-converter/releases/download/v1.8.0/ascii-image-converter_macOS_amd64_64bit.tar.gz"
      sha256 "01af7c0b161aa178e8847b65ded2b484ef3350d2812b7cb933098a0e315a9354"
    end
    if Hardware::CPU.arm?
      url "https://github.com/TheZoraiz/ascii-image-converter/releases/download/v1.8.0/ascii-image-converter_macOS_arm64_64bit.tar.gz"
      sha256 "27f6652c85d792a8dd19254fbc66907abd293859c661091e28f43cdc4a45578d"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/TheZoraiz/ascii-image-converter/releases/download/v1.8.0/ascii-image-converter_Linux_amd64_64bit.tar.gz"
      sha256 "b13ea97aad3267245bbab164901ab3f6dfc74b4573ff8eac2566e6dc1b440ee3"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/TheZoraiz/ascii-image-converter/releases/download/v1.8.0/ascii-image-converter_Linux_armv6_32bit.tar.gz"
      sha256 "0a181f6bfc8ca1da57ca62942f2a6050dd8f5be5bb0ec9c468b2e1d6b7f51b0f"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TheZoraiz/ascii-image-converter/releases/download/v1.8.0/ascii-image-converter_Linux_arm64_64bit.tar.gz"
      sha256 "b9a18ce863e8c9a1ead17171d6d44f7b17ac6fda5a3024745ed3f328b7b47d89"
    end
  end

  def install
    bin.install "ascii-image-converter"
  end

  test do
    system "#{bin}/ascii-image-converter --version"
  end
end
