# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AsciiImageConverter < Formula
  desc "Convert images into ascii art"
  homepage "https://github.com/TheZoraiz/ascii-image-converter"
  version "1.4.1-next"
  license "Apache 2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TheZoraiz/ascii-image-converter/releases/download/v1.4.1/ascii-image-converter_macOS_amd64_64bit.tar.gz"
      sha256 "9c185bfad027d070ff39e615dcada5e256e1d96e76067c5789cef0dfdbae4f68"
    end
    if Hardware::CPU.arm?
      url "https://github.com/TheZoraiz/ascii-image-converter/releases/download/v1.4.1/ascii-image-converter_macOS_arm64_64bit.tar.gz"
      sha256 "9676a567c7e8653a1e8948270a64eb2c233c561f8d64e46e0717aeaf8f16af88"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/TheZoraiz/ascii-image-converter/releases/download/v1.4.1/ascii-image-converter_Linux_amd64_64bit.tar.gz"
      sha256 "f69f1080eafda4197e66910c534d8fd8f2df780033f14a5db6da348d38d8c941"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/TheZoraiz/ascii-image-converter/releases/download/v1.4.1/ascii-image-converter_Linux_arm_32bit.tar.gz"
      sha256 "e4b8a03141395d826aff2a470df3c8ce151e11981d3bebead94426dd3c31984c"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TheZoraiz/ascii-image-converter/releases/download/v1.4.1/ascii-image-converter_Linux_arm64_64bit.tar.gz"
      sha256 "5a09eabe6acefe06ce5686afac233a75694c2895cf860599fb37da2774963469"
    end
  end

  def install
    bin.install "ascii-image-converter"
  end

  test do
    system "#{bin}/ascii-image-converter --version"
  end
end
